/* eslint-disable camelcase */

/**
 * This default scheme matches the layout generated by this tool and can be used
 * for any generated CSV glossary. Manually created/downloaded CSV glossaries will
 * require a custom scheme.
 */
export const defaultScheme = {
  term_en: 0,
  description_en: 1,
  "term_zh-CN": 2,
  term_ru: 3,
  term_ko: 4,
  term_pl: 5,
  term_uk: 6,
};
